//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web_banvemaybay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Binhluan
    {
        public int id { get; set; }
        public string binhluan1 { get; set; }
        public Nullable<int> idtaikhoan { get; set; }
        public Nullable<int> idTraloi { get; set; }
        public Nullable<System.DateTime> ngaybl { get; set; }
        public Nullable<int> sosao { get; set; }
    
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
