//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web_banvemaybay.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Chuyenbay
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Chuyenbay()
        {
            this.Ve = new HashSet<Ve>();
        }
        [DisplayName("Mã chuyến bay")]
        public int IDchuyenbay { get; set; }
        [DisplayName("Điểm đi")]
        public string Diadiemdi { get; set; }
        [DisplayName("Điểm đến")]
        public string Diadiemden { get; set; }
        [DisplayName("Ngày đi")]
        public Nullable<System.DateTime> Ngaydi { get; set; }
        [DisplayName("Ngày về")]
        public Nullable<System.DateTime> Ngayve { get; set; }
        [DisplayName("Giá chuyến")]
        public double Giatien { get; set; }
        public Nullable<int> IDhang { get; set; }
        [DisplayName("Số vé Phổ thông")]
        public Nullable<int> PhoThong { get; set; }
        [DisplayName("Số vé Thương gia")]
        public Nullable<int> ThuongGia { get; set; }
    
        public virtual HangHK HangHK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ve> Ve { get; set; }
    }
}
