//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web_banvemaybay.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaiKhoan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TaiKhoan()
        {
            this.Dattruoc = new HashSet<Dattruoc>();
        }
    
        public int IDtaikhoan { get; set; }
        public string Password { get; set; }
        public string ConfirmPassword { get; set; }
        public string HovaTen { get; set; }
        public string Email { get; set; }
        public Nullable<int> SDT { get; set; }
        public Nullable<int> IDchucvu { get; set; }
    
        public virtual Chucvu Chucvu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dattruoc> Dattruoc { get; set; }
    }
}
