
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace web_banvemaybay.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Ve
{

    public int IDve { get; set; }

    public Nullable<int> IDdattruoc { get; set; }

    public Nullable<int> IDchuyenbay { get; set; }

    public Nullable<int> IDhanhkhach { get; set; }

    public Nullable<decimal> Giatien { get; set; }

    public string Tinhtrang { get; set; }

    public Nullable<int> HanhliID { get; set; }



    public virtual Dattruoc Dattruoc { get; set; }

    public virtual Hanhkhach Hanhkhach { get; set; }

    public virtual Hanhli Hanhli { get; set; }

    public virtual Chuyenbay Chuyenbay { get; set; }

}

}
